from langchain_community.llms import Ollama
from crewai import Agent, Task, Crew, Process
from database_schema import schema
from database_schema2 import schema2
from database_connector import db
import re
# Define model
model = Ollama(model="llama3")
# Define user input, user input must not be general
# user_input = "How many Category types are there? Get from the Category table schema"
# user_input = "How many User are there? Get from the User table schema"
user_input = "Listing the most popular Ticket types"
# user_input = "Who buy the most tickets?"
# user_input = "Who buy the most tickets? Try using the Checkout table"
# user_input = "Which event is has the most tickets sold?"
# Define agents
generator = Agent(
    role="Database Query Generator",
    goal="Generate optimal and syntactically correct SQL queries based on the given schema and user input specifications. Be concise and accurate. Do NOT make up information.",
    backstory="""
        You are an SQL expert.
        You're responsible for creating optimal and syntactically correct SQL query based on a given database schemas.
        You can not change the name of the tables and properties within the tables when creating the SQL query.
    """,
    verbose=True,
    allow_delegation=False,
    llm=model
)
extractor = Agent(
    role = "SQL Query Extractor",
    goal = """
        To extract only SQL query code block from a passage or text.
    """,
    backstory = """
        You are an SQL code block extractor expert.
        You're responsible for extracting SQL query code block from a passage or text.
        If there is an SQL code block already, you do NOT add any comment, leave it be.
    """,
    verbose=True,
    allow_delegation=False,
    llm=model
)
# Define tasks
generator_task = Task(
    description=f"""
        You work on this database schema: {schema2}. 
        Generate optimimal and syntactically correct SQL queries based on user specifications {user_input}.
    
        DO:
        - Use the exact name of tables and properties, they MUST be exactly the same in the query as in the schema.
        - ALWAYS look at the tables and tables' properties in the database schema to see what you can query.
        - Use only the column names you can see existing in the tables. 
        - Pay attention to which column is in which table.
        - Naming table must be unique.
        - ALWAYS use 'LIMIT' function to limit the out to 20 rows.
        - Use function to get the current date, if the question involves "today".
        - If there are tables need to be joined, you always use 'JOIN' function to join tables.
        - Query only the columns that are needed to answer the user question.
        - Unless the user specifies in the question specific columns to obtain, display for at most 5 significant columns. 
        - The order of the results to return the most informative data in the database. The schema's primary key(s) must always be used in SELECT query.
        - When 'GROUP BY', specifically check if enough essential columns
        - Return SQL query ONLY.
        Do NOT skip this step.

        Do NOT:
        - Query for columns or properties that do not exist.
        - Make or generate any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.
        - Use SQL subquery.
        - Change the table's name.
        - Use columns that not belong to table
        - Use SELECT *.
        - Use 'TOP 1'.
        - Duplicate table names.
        - Return any values beside the SQL query.
        Do NOT skip this step.
    """,
    agent=generator,
    expected_output="""
        An optimal and syntactically correct SQL query to retrieve relevant information from the database schema based on the content of the user input.
        Only the SQL query is returned. Nothing other than the SQL query is returned.
    """
)
extractor_task = Task(
    description = """
        You receive the output from 'generator' agent.
        You extract only the SQL code block from the passage or text.
    """,
    agent=extractor,
    expected_output = """
        The code block of SQL query generated by 'generator' agent.
        Only SQL query code block. No comment.
    """,
    context = [generator_task]
)
# Define crew
crew = Crew(
    agents=[generator, extractor],
    tasks=[generator_task, extractor_task],
    verbose=2,
    process=Process.sequential
)
# Kickoff the process and print the output
output = crew.kickoff()
print(output)

# print(f"""
#     Task completed!
#     Output: {generator_task.output.raw_output}
# """)

# try:
#     sql_query = ""
#     pattern_1 = re.compile(r'```sql(.*?)```', re.DOTALL)
#     pattern_2 = re.compile(r'```(.*?)```', re.DOTALL)
#     matches_1 = pattern_1.findall(output)
#     matches_2 = pattern_2.findall(output)
    
    
#     if len(matches_1) != 0:
#         sql_query = matches_1[0]  
#     elif len(matches_2) != 0:
#         sql_query = matches_2[0]
#     else:
#         print("> No value returns")

#     final = db.run(sql_query)
#     print(final)
# except Exception  as e:
#     print("> Please describe your request more specifically")
# finally:
#     print(output)


    